# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: python:3.13.2-bookworm
merge:
  script: |
    pip3 install -r requirements.txt
    /home/r/.local/bin/pytest --cov-fail-under=0
